demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: dbtpg # or database instead of dbname
      schema: public
      threads: 4
      connect_timeout: 10 # default 10 seconds      
