name: Run dbt

on:
  schedule:
    - cron: '0 1 * * 1'  # Runs at 1 AM every Monday
  workflow_dispatch:  # Allows manual triggering

env:
  DBT_PROFILES_DIR: ./dbt_pcomp
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install -r ./dbt_pcomp/requirements.txt

    - name: Run dbt
      run: |
        dbt run --project-dir ./dbt_pcomp
