name: Pcomp Scraper

on:
  schedule:
    - cron: '0 1 * * 1'  # Runs at 1 AM every Monday
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests fake-useragent pandas-gbq google-auth

    - name: Run Enterkomputer scraper
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: python scraping/enterkomputer.py

    - name: Run Viraindo scraper
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: python scraping/viraindo.py